### ISSUE TITLE
Changing the src doesn't trigger attributeChanged()

### ISSUE THREAD

**Issue by emielbeinema** [streetturtle/pdf-element#14]
### Description

Changing the value of the src-property (for example by using a databinding) doesn't trigger execution of the attributeChanged() method. This results in the PDF not being displayed.

### Expected outcome

When the src-property is changed, the pdf-element should load the PDF at the src URL and display it.

### Actual outcome

When the src-property is changed, nothing happens.

### Proposed solution

This appears to be the expected behaviour. While `notify: true` is set on the src-property, this only fires the `src-changed` event on change of the property ([polymer-docs: notify](https://www.polymer-project.org/1.0/docs/devguide/properties#notify)).

When we set `reflectToAttribute: true` instead, the method is executed and the PDF loads as expected.

**Comment by streetturtle** [comment]
Hi! Thank you for raising this issue, and sorry for such late reply.
I'm afraid I cannot reproduce this issue. On the [demo](http://pavelmakhov.com/pdf-element/components/pdf-element/demo/) page, in the second example I'm doing exactly that - change `src` attribute of the element and it works there.
Could you please clarify how exactly you change the `src` attribute of the element.
Thanks!

**Comment by atifwaqar** [comment]
same thing happening here. here is my code: 
```html
<pdf-element src="{{model.SelectedPdf}}" width=50%></pdf-element>
```

it works fine if my code is something like this:
```html
<pdf-element src="http://......pdf" width=50%></pdf-element>
```

but if I have the same url in `SelectedPdf` variable, it does not work. 
Also the value in `SelectedPdf` gets null when i have this line of code:
```html
<pdf-element src="{{model.SelectedPdf}}" width=50%></pdf-element>
```

**Comment by atifwaqar** [comment]
Here is my code, i made a component just to simplify 
```html
<link rel="import" href="/sys/paper-button/paper-button.html" />
<link rel="import" href="/sys/pdf-element/pdf-element.html" />
<dom-module id="pdf-test">
    <template>
        <paper-button raised id="one" on-tap="one">PDF One</paper-button>
        <paper-button raised id="another">PDF Two</paper-button>
        <pdf-element id="pdf" show-spinner src = "https://www.w3.org/TR/xhtml1/xhtml1.pdf"></pdf-element>
    </template>
    <script>
        Polymer({
            is: "pdf-test",
            one: function (e) {
                debugger;
                this.$.pdf.src = "https://www.w3.org/TR/1998/REC-html40-19980424/html40.pdf";
                debugger;
            },
            two: function (e) {
                debugger;
                this.$.pdf.src = "https://www.w3.org/TR/xhtml1/xhtml1.pdf"
                debugger;
            }
        });
    </script>
</dom-module>
```

I can see that src value is changes, but it does not update the viewer.
Please observer value `this.$.pdf.src`
![image](https://cloud.githubusercontent.com/assets/4388707/24806497/5e18160a-1bb5-11e7-92e8-12110d3ccc63.png)


![image](https://cloud.githubusercontent.com/assets/4388707/24806505/636dba42-1bb5-11e7-88ea-c5e5905bc8d5.png)

**Comment by streetturtle** [comment]
@atifwaqar could you please try now - I've merger PR [#15](https://github.com/streetturtle/pdf-element/pull/15). I think it should work now.

**Comment by atifwaqar** [comment]
Nicely done. Thank you for helping @streetturtle :)
