### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by tontowi22** [streetturtle/pdf-element#9]
hello im new with polymer and i try to use your element, but the pdf preview not working but when i dowload the pdf is working, this my code:

![screenshot from 2016-11-24 15 48 28](https://cloud.githubusercontent.com/assets/16931133/20591910/85063a9c-b25d-11e6-9371-d4278f013ec6.png)

**Comment by streetturtle** [comment]
Hi @tontowi22, I'll have a look this weekend. 
By the way, have you checked the js console (in developer tools of Chrome/Firefox). Is there any errors?

**Comment by streetturtle** [comment]
Reopen this issue if the problem still exists.
